import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import img from "../img/download.jpeg";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Military",
  description: "Generated by IceCream",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} relative w-full h-[100vh]`}
      >
        <div className="w-full h-full absolute top-0 left-0 opacity-[30%] -z-10">
          <Image
            src={img}
            alt="Picture of the author"
            className="w-full h-full"
          />
        </div>
        {children}
      </body>
    </html>
  );
}
